server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/card_benefits}
    username: ${DATABASE_USERNAME:card_benefits}
    password: ${DATABASE_PASSWORD:card_benefits}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
