create table if not exists credit_cards (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    issuer varchar(255) not null,
    network varchar(255),
    annual_fee_cents integer not null,
    is_business boolean not null,
    description varchar(500)
);

create table if not exists reward_categories (
    id bigint generated by default as identity primary key,
    card_id bigint not null references credit_cards(id) on delete cascade,
    name varchar(255) not null,
    earn_rate varchar(100) not null,
    details varchar(500)
);

create table if not exists benefits (
    id bigint generated by default as identity primary key,
    card_id bigint not null references credit_cards(id) on delete cascade,
    type varchar(50) not null,
    name varchar(255) not null,
    description varchar(500),
    value_cents integer,
    value_text varchar(255)
);
